/**
 * Created by Administrator on 2018/3/7.
 */
import {dispatch} from '../store';
let defaultState = {
    menuData:[
        [
            {
                iconCls:'code-o',
                path:'/food',
                text:'美食'
            },
            {
                iconCls:'code-o',
                path:'/cs',
                text:'超市'
            },
            {
                iconCls:'code-o',
                path:'/fruit',
                text:'生鲜果蔬'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试1'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试1'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试1'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试1'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试1'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试1'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试1'
            }
        ],
        [
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试21'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试2'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试2'
            }
        ],
        [
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试321'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试32'
            },
            {
                iconCls:'code-o',
                path:'/aa',
                text:'测试32'
            }
        ]
    ],
    czyhData:[
        {
            title:'单独撒a',
            intro:'是经典款',
            src:'img/1.jpg'
        },
        {
            title:'单独撒a',
            intro:'是经典款',
            src:'img/1.jpg'
        },
        {
            title:'单独撒a',
            intro:'是经典款',
            src:'img/1.jpg'
        },
        {
            title:'单独撒a',
            intro:'是经典款',
            src:'img/1.jpg'
        },
        {
            title:'单独撒a',
            intro:'是经典款',
            src:'img/1.jpg'
        },
        {
            title:'单独撒a',
            intro:'是经典款',
            src:'img/1.jpg'
        }
    ]
};

export let homeData = (state = defaultState,action = {}) => {
    let func = reducer[action.type];
    if(typeof func === 'function'){
        state = wt.clone(state);
        func(state,action);
    }
    return state;
};

let reducer = {

};
